### ISSUE TITLE
for Council, suppress warnings and messages in Rmd

### ISSUE THREAD

**Issue by sgaichas** [gavinfay/fluke-mafmc-recdisc#12]
Is there a label for "minor edit?" :-)

at this line

https://github.com/gavinfay/fluke-mafmc-recdisc/blob/d6ad3431e65fdff4659a74fd5b4a957f65ca0c70/summary-metrics.Rmd#L9

could add 
```
                                                    ,
                      message = FALSE,
                      warning = FALSE)
```

(would edit myself but I'm afraid of breaking your workflow)

**Comment by gavinfay** [comment]
Thanks Sarah!
